[package]
name = "server_updater"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.2"
md5 = "0.7.0"
reqwest = { version = "0.11.23", features = ["native-tls-vendored", "blocking"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
