name: Publish binaries to GitHub release

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    branches:
      - master

jobs:
  check-version:
    name: Check the version validity
    runs-on: ubuntu-latest
    # No need to check the version for dry run (cron)
    steps:
      - uses: actions/checkout@v3
      # Check if the tag has the v<nmumber>.<number>.<number> format.
      # If yes, it means we are publishing an official release.
      # If no, we are releasing a RC, so no need to check the version.
      - name: Check tag format
        if: github.event_name == 'release'
        id: check-tag-format
        run: |
          escaped_tag=$(printf "%q" ${{ github.ref_name }})

          if [[ $escaped_tag =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "stable=true" >> $GITHUB_OUTPUT
          else
            echo "stable=false" >> $GITHUB_OUTPUT
          fi
      - name: Check release validity
        if: github.event_name == 'release' && steps.check-tag-format.outputs.stable == 'true'
        run: bash .github/scripts/check-release.sh

  publish-linux:
    name: Publish binary for Linux
    runs-on: ubuntu-latest
    needs: check-version
    container:
      # Use ubuntu-18.04 to compile with glibc 2.27
      image: ubuntu:18.04
    steps:
      - uses: actions/checkout@v3
      - name: Install needed dependencies
        run: |
          apt-get update && apt-get install -y curl
          apt-get install build-essential -y
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build
        run: cargo build --release --locked -p boomerang_server; cargo build --release --locked -p server_updater
      # No need to upload binaries for dry run (cron)
      - name: Upload server binary
        uses: svenstaro/upload-release-action@2.7.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/server
          asset_name: boomerang-server-linux-amd64
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload server updater binary
        uses: svenstaro/upload-release-action@2.7.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/server_updater
          asset_name: boomerang-server-updater-linux-amd64
          tag: ${{ github.ref }}
          overwrite: true

  publish-aarch64:
    name: Publish binary for aarch64
    runs-on: ubuntu-latest
    needs: check-version
    container:
      # Use ubuntu-18.04 to compile with glibc 2.27
      image: ubuntu:18.04
    strategy:
      matrix:
        include:
          - target: aarch64-unknown-linux-musl
            asset_name: boomerang-server-linux-aarch64
            asset_name_updater: boomerang-server-updater-linux-aarch64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install needed dependencies
        run: |
          apt-get update -y && apt upgrade -y
          apt-get install -y curl build-essential gcc-aarch64-linux-gnu musl
      - name: Set up Docker for cross compilation
        run: |
          apt-get install -y curl apt-transport-https ca-certificates software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
          add-apt-repository "deb [arch=$(dpkg --print-architecture)] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          apt-get update -y && apt-get install -y docker-ce
      - name: Installing Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          target: ${{ matrix.target }}
          override: true
      - name: Configure target aarch64 GNU
        ## Environment variable is not passed using env:
        ## LD gold won't work with MUSL
        # env:
        #   JEMALLOC_SYS_WITH_LG_PAGE: 16
        #   RUSTFLAGS: '-Clink-arg=-fuse-ld=gold'
        run: |
          echo 'JEMALLOC_SYS_WITH_LG_PAGE=16' >> $GITHUB_ENV
      - name: Cargo build boomerang_server
        uses: actions-rs/cargo@v1
        with:
          command: build
          use-cross: true
          args: --release --target ${{ matrix.target }} -p boomerang_server
        env:
          CROSS_DOCKER_IN_DOCKER: true
      - name: Cargo build server_updater
        uses: actions-rs/cargo@v1
        with:
          command: build
          use-cross: true
          args: --release --target ${{ matrix.target }} -p server_updater
        env:
          CROSS_DOCKER_IN_DOCKER: true
      - name: Upload the server binary to release
        # No need to upload binaries for dry run (cron)
        uses: svenstaro/upload-release-action@2.7.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ matrix.target }}/release/server
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload the server updater binary to release
        # No need to upload binaries for dry run (cron)
        uses: svenstaro/upload-release-action@2.7.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ matrix.target }}/release/server_updater
          asset_name: ${{ matrix.asset_name_updater }}
          tag: ${{ github.ref }}
          overwrite: true
